# -*- coding: utf-8 -*-
"""analisis siswa

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-bXjJJGE0jA8pN0Is9pdeSJyVc_DcfWd
"""

import streamlit as st
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# ==========================================================
# INPUT DATA
# ==========================================================
uploaded_file = st.file_uploader("Upload file Excel", type=["xlsx"])

if uploaded_file is None:
    st.warning("Silakan upload file Excel terlebih dahulu.")
    st.stop()

# ==========================================================
# MEMBACA DATA
# ==========================================================
try:
    df = pd.read_excel(uploaded_file)
    indikator = df.apply(pd.to_numeric, errors="coerce")
except Exception as e:
    st.error(f"Gagal membaca file: {e}")
    st.stop()

# ===============================
# INFORMASI DATA
# ===============================

print("Informasi Dataset:")
display(df.info())

print("\nStatistik Deskriptif Awal:")
display(df.describe())

# ===============================
# IDENTIFIKASI KOLOM SOAL
# ===============================

soal_columns = [col for col in df.columns if "Soal" in col]

print("Jumlah Soal:", len(soal_columns))
print("Daftar Kolom Soal:", soal_columns)

# ===============================
# HITUNG TOTAL NILAI
# ===============================

df["Total_Nilai"] = df[soal_columns].sum(axis=1)

df.head()

# ===============================
# KATEGORI NILAI
# ===============================

def kategori_nilai(nilai):
    if nilai >= 85:
        return "A"
    elif nilai >= 75:
        return "B"
    elif nilai >= 65:
        return "C"
    elif nilai >= 55:
        return "D"
    else:
        return "E"

df["Kategori"] = df["Total_Nilai"].apply(kategori_nilai)

df.head()

# ===============================
# STATISTIK DESKRIPTIF
# ===============================

print("Statistik Total Nilai:")
display(df["Total_Nilai"].describe())

print("\nDistribusi Kategori:")
display(df["Kategori"].value_counts())



